# Generated by Django 5.0.2 on 2024-11-10 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name_plural': 'Wish List'},
        ),
    ]
